language: clang
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - lcov

install:
  - gem install coveralls-lcov

script:
  - make c

after_success:
  - coveralls-lcov /home/travis/build/tecnickcom/binsearch/target/test/coverage/binsearch.info
