# Dockerfile
#
# Linux development environment
#
# Extend the tecnickcom/alldev image defined in
# https://github.com/tecnickcom/alldev
# ------------------------------------------------------------------------------

FROM tecnickcom/alldev
MAINTAINER info@tecnick.com
ENV PATH=/usr/local/go/bin/:$PATH
