package:
  name: binsearch
  version: 3.0.7.1

source:
  path: ..

requirements:
  build:
    - setuptools
  run:
    - python

test:
  requires:
    - python
    - setuptools
    - coverage
    - pytest
    - pytest-pep8
    - pytest-cov
    - pytest-benchmark
  imports:
    - binsearch

about:
  home: https://github.com/tecnickcom/binsearch
  license: MIT
