package:
  name: binsearch
  version: 8.2.3

source:
  path: ../..

build:
  number: 1

requirements:
  host:
    - python
    - setuptools
  build:
    - {{ compiler('c') }}
  run:
    - python

test:
  requires:
    - python
    - setuptools
    - coverage
    - pytest
    - pytest-cov
    - pytest-benchmark
    - pycodestyle
  imports:
    - binsearch

about:
  home: https://github.com/tecnickcom/binsearch
  license: MIT
  license_file: LICENSE
  summary: Binary search for constant-lenght binary files.
